-- =============================================================================
-- Migration: Drop Redundant Indexes in Pedidos Database (barraca)
-- Generated by sql-audit-mcp engine
-- =============================================================================
-- NOTE FOR PRODUCTION EXECUTION:
-- In PostgreSQL, DROP INDEX CONCURRENTLY acquires an SHARE UPDATE EXCLUSIVE lock
-- instead of an ACCESS EXCLUSIVE lock, preventing blocking of SELECT, INSERT,
-- UPDATE, and DELETE operations during execution.
--
-- IMPORTANT:
-- 1. DROP INDEX CONCURRENTLY cannot be executed inside a multi-statement transaction
--    block (BEGIN ... COMMIT). Run this script with autocommit enabled (psql default).
-- 2. If using an ORM like SQLAlchemy / Alembic, remember to remove the duplicate
--    `index=True` or `Index(...)` definitions from the Python models to avoid
--    Alembic attempting to recreate them in future autogenerated migrations.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SECTION 1: Exact Duplicates (ix_* duplicates of explicit idx_* indexes)
-- -----------------------------------------------------------------------------

-- Table: pedidos
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pedidos_cliente_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pedidos_repartidor_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pedidos_usuario_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pedidos_empresa_id;

-- Table: pedido_items
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pedido_items_pedido_id;

-- Table: entrega_eventos
DROP INDEX CONCURRENTLY IF EXISTS public.ix_entrega_eventos_pedido_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_entrega_eventos_empresa_id;

-- Table: pagos
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pagos_cliente_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pagos_empresa_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_pagos_pedido_id;

-- Table: cliente_direcciones
DROP INDEX CONCURRENTLY IF EXISTS public.ix_cliente_direcciones_empresa_id;
DROP INDEX CONCURRENTLY IF EXISTS public.ix_cliente_direcciones_cliente_id;

-- -----------------------------------------------------------------------------
-- SECTION 2: Standalone Index Duplicate of Existing UNIQUE Constraint
-- -----------------------------------------------------------------------------

-- Table: empresas (covered by unique constraint 'empresas_slug_key' on slug)
DROP INDEX CONCURRENTLY IF EXISTS public.idx_empresa_slug;

-- -----------------------------------------------------------------------------
-- SECTION 3: Single-column Indexes Covered by Leading Column in Composite UNIQUE
-- (Optional / Recommended: PostgreSQL B-tree can satisfy WHERE empresa_id = ?
-- queries using the composite unique index prefix).
-- -----------------------------------------------------------------------------

-- Table: configuracion (covered by uq_config_empresa_clave on (empresa_id, clave))
-- DROP INDEX CONCURRENTLY IF EXISTS public.ix_configuracion_empresa_id;

-- Table: usuarios (covered by uq_usuario_empresa_email on (empresa_id, email))
-- DROP INDEX CONCURRENTLY IF EXISTS public.ix_usuarios_empresa_id;

-- Table: clientes (covered by uq_cliente_empresa_celular on (empresa_id, celular))
-- DROP INDEX CONCURRENTLY IF EXISTS public.ix_clientes_empresa_id;
