"""Infrastructure layer for SQL Audit."""

from sql_audit.infrastructure.queries import (
    SQL_DEAD_TUPLES_ALL_PSYCOPG,
    SQL_DEAD_TUPLES_ASYNCPG,
    SQL_DEAD_TUPLES_SCHEMAS_PSYCOPG,
    SQL_HOT_ASYNCPG,
    SQL_HOT_PSYCOPG,
    SQL_INVALID_INDEXES_ALL_PSYCOPG,
    SQL_INVALID_INDEXES_ASYNCPG,
    SQL_INVALID_INDEXES_SCHEMAS_PSYCOPG,
    SQL_LOW_USAGE_ASYNCPG,
    SQL_LOW_USAGE_PSYCOPG,
    SQL_REDUNDANT_ASYNCPG,
    SQL_REDUNDANT_PSYCOPG,
    SQL_UNINDEXED_FKS_ALL_PSYCOPG,
    SQL_UNINDEXED_FKS_ASYNCPG,
    SQL_UNINDEXED_FKS_SCHEMAS_PSYCOPG,
)

__all__ = [
    "SQL_DEAD_TUPLES_ALL_PSYCOPG",
    "SQL_DEAD_TUPLES_ASYNCPG",
    "SQL_DEAD_TUPLES_SCHEMAS_PSYCOPG",
    "SQL_HOT_ASYNCPG",
    "SQL_HOT_PSYCOPG",
    "SQL_INVALID_INDEXES_ALL_PSYCOPG",
    "SQL_INVALID_INDEXES_ASYNCPG",
    "SQL_INVALID_INDEXES_SCHEMAS_PSYCOPG",
    "SQL_LOW_USAGE_ASYNCPG",
    "SQL_LOW_USAGE_PSYCOPG",
    "SQL_REDUNDANT_ASYNCPG",
    "SQL_REDUNDANT_PSYCOPG",
    "SQL_UNINDEXED_FKS_ALL_PSYCOPG",
    "SQL_UNINDEXED_FKS_ASYNCPG",
    "SQL_UNINDEXED_FKS_SCHEMAS_PSYCOPG",
]
